name: clicker-bot
channels:
  - conda-forge
  - nvidia
  - pytorch
  - anaconda
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - pytorch=1.13.1
  - torchvision>=0.8.1,!=0.13.0
  - cuda-toolkit=11.7.1
  - cudatoolkit
  - scikit-learn>=0.19.2
  - pip:
    - matplotlib>=3.2.2
    - numpy>=1.18.5,<1.24.0
    - opencv-python>=4.1.1
    - Pillow>=7.1.2
    - PyYAML>=5.3.1
    - requests>=2.23.0
    - scipy>=1.4.1
    - tqdm>=4.41.0
    - protobuf<4.21.3
    - tensorboard>=2.4.1
    - pandas>=1.1.4
    - seaborn>=0.11.0
    - onnx>=1.9.0
    - onnxruntime-gpu
    - onnx-simplifier>=0.3.6
    - onnxsim
    - ipython
    - psutil
    - dxcam
    - pynput
    - pygame
    - pyautogui
    - jupyter
    